### ISSUE TITLE
Script no longer works on Linux

### ISSUE THREAD

**Issue by NullDott** [sprngr/aseprite-record#13]
## Issue

![image](https://github.com/sprngr/aseprite-record/assets/101472580/e35d3d71-f9c6-4551-b823-755438bb662d)

So I upgraded to `Aseprite v1.3.7` and now the script doesn't work anymore, it throws an assertion when trying to create the folder for the snapshots, I don't if it only affects Linux, but it may be the case since this was added:

![image](https://github.com/sprngr/aseprite-record/assets/101472580/01d1e33c-6f63-431c-ae2a-9126f0a9ff7e)

Maybe it is related, maybe not, but the thing is I can no longer record my progress because it cannot create the folder.

Could you help me?

**System:** Linux Mint 21.3
**Aseprite:** 1.3.7

**Comment by sprngr** [comment]
@NullDott Sorry, just seeing this issue now. Let me work on getting a linux setup together to see if I can reproduce it and I'll get back to you.

**Comment by sprngr** [comment]
@NullDott Following up, I was able to reproduce the error in Linux. I have pushed up a fix that I was able to confirm working in v3.4.2 on github and itch. Thanks for filing the issue.

**Comment by NullDott** [comment]
Yo, I just wanted to say thanks!!! The script works like a charm once again!
