### ISSUE TITLE
Unable to record in Color Mode "Indexed"

### ISSUE THREAD

**Issue by vegedot** [sprngr/aseprite-record#9]
Recording in "Indexed" color mode does not retain colors (only transparent and black)
Is it possible to record in "Indexed" mode while retaining color?

or is it due to my environment?

**Comment by sprngr** [comment]
@vegedot Sorry for the late response, let me look into this and I'll get back to you.

**Comment by sprngr** [comment]
@vegedot A fix has been tagged as part of v3.4 that has added support for indexed colormode on a sprite. Thank you for raising the issue. You can download it via https://github.com/sprngr/aseprite-record/archive/refs/tags/v3.4.zip

**Comment by vegedot** [comment]
@sprngr Nice!! I have been waiting for this moment. Now I can use this awesome script!
Thank you for your work ❤
